### PR TITLE
chore: add code ql configuration

### PR DESCRIPTION
**Pull request by bmunguli**
## Description
Add custom configuration file for codeql
- Exclude tests from scanning to optimize pipeline runs
- Exclude warning and recommandations to have focused reports
- Exclude:  java/spring-disabled-csrf-protection check as this application is backend and disabling csrf is intended. 
This API is exclusively used by non-browser clients. 

## Pre-review checks

Please ensure to do as many of the following checks as possible, before asking for committer review:

- [X] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [X] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files

### CODE REVIEW

**Comment by tunacicek** [comment]
@agg3fe : Is that ok for you too?

**Review by agg3fe — APPROVED** [review]
LGTM

**Comment by agg3fe** [comment]
> @agg3fe : Is that ok for you too?

Yes it's fine from my side.

**Review by tunacicek — APPROVED** [review]
LGTM

**Pull request merged**
